name: flutter_google_places_sdk_web
description: The web implementation of Flutter plugin for google places sdk
version: 0.1.3+5
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_web
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_google_places_sdk_platform_interface:
    git:
      url: https://github.com/Arbo-Works/flutter_google_places_sdk
      ref: develop-2023.08.16-09.36
      path: flutter_google_places_sdk_platform_interface
  js: ^0.6.4
  google_maps: ^6.2.0
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter:
  plugin:
    platforms:
      web:
        fileName: flutter_google_places_sdk_web.dart
        pluginClass: FlutterGooglePlacesSdkWebPlugin
