name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.3.2+9
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: 0.2.4+3
  flutter_google_places_sdk_web:
    git:
      url: https://github.com/Arbo-Works/flutter_google_places_sdk
      ref: develop-2023.08.16-09.36
      path: flutter_google_places_sdk_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_google_places_sdk_android
      ios:
        default_package: flutter_google_places_sdk_ios
      web:
        default_package: flutter_google_places_sdk_web
      windows:
        default_package: flutter_google_places_sdk_windows
      linux:
        default_package: flutter_google_places_sdk_linux
      macos:
        default_package: flutter_google_places_sdk_macos
